pipeline {
    agent any

    stages {
        stage('Compilation') {
            steps {
                sh 'make'
            }
        }
        stage('Test') {
            steps {
                sh 'make test'
            }
        }
     }
}

