pipeline {
    agent any

    stages {
        stage('Compilation') {
            steps {
                sh 'make'
            }
        }
        stage('Test') {
            steps {
                sh 'make test'
            }
        }
        stage('Run') {
            steps {
                sh './tribulle 8 4 6 3 14 5 3 8'
            }
        }
        stage('Deploy') {
            steps {
                sh 'PREFIX=dist make install'
            }
        }
        stage('Clean') {
            steps {
                sh 'make clean'
            }
        }
    }
}

