pipeline {
    agent any

    stages {
        stage('Compilation') {
            steps {
                sh 'make'
            }
        }
        stage('Test') {
            steps {
                sh 'make test'
            }
        }
        stage('Profile') {
            steps {
                sh 'valgrind ./tribulle 8 4 6 3 14 5 3 8'
            }
        }
        stage('Clean') {
            steps {
                sh 'make clean'
            }
        }
    }
}

